#!/usr/bin/env bash

docker-compose down

chown -R 1000:1000 .
chmod -R 775 .
chown -R 472 config/grafana
chown -R 65534 config/prometheus
chown -R 472 data/grafana
chown -R 65534 data/prometheus

docker-compose up -d exporter
docker-compose up -d prometheus
docker-compose up -d grafana
docker-compose up -d php
docker-compose up -d nginx
docker-compose up -d timer
docker-compose up -d game.0.0
docker-compose up -d game.1.0
docker-compose up -d game.m1.0
docker-compose up -d game.0.1
docker-compose up -d game.0.m1
docker-compose up -d game.1.1
docker-compose up -d game.m1.1
docker-compose up -d game.1.m1
docker-compose up -d game.m1.m1
